export const displayValues = [
  { title: 'inline', description: 'Displays an element as an inline element' },
  { title: 'block', description: 'Displays an element as a displayContents element' },
  { title: 'contents', description: 'Makes the container disappear, making the child elements children of the element the next level up in the DOM' },
  { title: 'flex', description: 'Displays an element as a displayContents-level flex container' },
  { title: 'grid', description: 'Displays an element as a displayContents-level grid container' },
  { title: 'inline-displayContents', description: 'Displays an element as an inline-level displayContents container. The element itself is formatted as an inline element, but you can apply height and width values' },
  { title: 'inline-flex', description: 'Displays an element as an inline-level flex container' },
  { title: 'inline-grid', description: 'Displays an element as an inline-level grid container' },
  { title: 'inline-table', description: 'The element is displayed as an inline-level table' },
  { title: 'list-item', description: 'Let the element behave like a <li> element' },
  { title: 'run-in', description: 'Displays an element as either displayContents or inline, depending on context' },
  { title: 'table', description: 'Let the element behave like a <table> element' },
  { title: 'table-caption', description: 'Let the element behave like a <caption> element' },
  { title: 'table-column-group', description: 'Let the element behave like a <colgroup> element' },
  { title: 'table-header-group', description: 'Let the element behave like a <thead> element' },
  { title: 'table-footer-group', description: 'Let the element behave like a <tfoot> element' },
  { title: 'table-row-group', description: 'Let the element behave like a <tbody> element' },
  { title: 'table-cell', description: 'Let the element behave like a <td> element' },
  { title: 'table-column', description: 'Let the element behave like a <col> element' },
  { title: 'table-row', description: 'Let the element behave like a <tr> element' },
  { title: 'none', description: 'The element is completely removed' },
  { title: 'initial', description: 'Sets this property to its default value' },
  { title: 'inherit', description: 'Inherits this property from its parent element' }
];